analytics:
  google: UA-78822783-1
color:
  brandColors:
    - '#F3CB69'
    - '#424242'
    - '#FFFFFF'
    - '#D5AF5C'
    - '#3B3B3B'
  brandStrength: 0.668918
  lightness: 0.489646
  rhythmicContrast: 0.622748
  saturation: 0.380013
cta: {}
layout_spectrum: 0.205368
name: 3301Hakuba
opengraph: {}
purpose: []
typography_spectrum: 0.322721
